version: "3.8"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: trieu-mock-project-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: trieu_mock_project_go
    ports:
      - "3306:3306"
    volumes:
      - trieu_mock_project_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - trieu-mock-project-app-network

  mail-server:
    platform: linux/x86_64
    image: mailhog/mailhog:v1.0.1
    container_name: trieu-mock-project-mail-server
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - trieu-mock-project-app-network

  redis:
    platform: linux/x86_64
    image: redis:7-alpine
    container_name: trieu-mock-project-redis
    ports:
      - "6379:6379"
    volumes:
      - trieu_mock_project_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trieu-mock-project-app-network

volumes:
  trieu_mock_project_mysql_data:
  trieu_mock_project_redis_data:

networks:
  trieu-mock-project-app-network:
    driver: bridge
